version: '2'
services:
  yopla-app:
    image: yopla
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://yopla-postgresql:5432/yopla
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://yopla-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://yopla-elasticsearch:9200
    ports:
      - 8080:8080
  yopla-postgresql:
    extends:
      file: postgresql.yml
      service: yopla-postgresql
  yopla-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: yopla-elasticsearch
